### ISSUE TITLE
How is this imported?

### ISSUE THREAD

**Issue by chickenandpork** [change-engine/terraform-provider-slack-token#47]
Please document import.

Available documentation is fairly laconic:
```
resource "slack-token_refresh" "example" {
  # This resource _must_ be imported using the Slack Refresh token
}
```

With a slack website-generated page showing "Your App Configuration Tokens", with "Access Token" and "Refresh Token", how exactly do I use those to import themselves?  Some `terraform state" manual write?

Even a screen cap of a successful import by CLI would be helpful.

Thanks!

**Comment by BarnabyShearer** [comment]
On https://api.slack.com/authentication/config-tokens click generate token then copy the Refresh token. It should start `xoxe-`.
Then you can `terraform import slack-token_refresh.example xoxe-`
