### ISSUE TITLE
Unable to rotate token, got error: json: Unmarshal(non-pointer provider.refreshResponse)

### ISSUE THREAD

**Issue by chickenandpork** [change-engine/terraform-provider-slack-token#50]
Ran into the error `Unable to rotate token, got error: json: Unmarshal(non-pointer provider.refreshResponse)` at title using provider v-0.1.1

We were experiencing a failure to refresh the rotating tokens;
Remediated by:
1. `state rm` the old state,
2. `import <object> "xoxe-1-..."` the new token (<object> being the ID of the `slack-token_refresh`) [EDIT: was a typo "xoxo-1-" before]
3. `terraform apply -auto-approve     -target <object>` to test rotation

This error message results; unsure how to diagnose further.  I can see that this *might* be https://github.com/change-engine/terraform-provider-slack-token/blob/main/internal/provider/refresh_resource.go#L107 but I'm unsure how to collect and report the content sent back from the service.

Reverting to v0.1 seems to have mitigated.

**Comment by BarnabyShearer** [comment]
The intention of this provider is to manage "App configuration tokens" generated on https://api.slack.com/authentication/config-tokens. They should start `xoxe-1-` rather then `xoxo-1-`.

**Comment by chickenandpork** [comment]
Checking my refresh token (by dumping into a `local_file`), it is indeed the `xoxe-1-`, my typo above.

**Comment by BarnabyShearer** [comment]
Sorry to check but `xoxo-` are another valid type of Slack token. The provider provide very useful logs in general for the risk of leaking secrets. `TF_LOG=debug terraform apply` dose give more information.
I can reproduce however so the should be a fix out soon.

**Comment by BarnabyShearer** [comment]
This should now be working in v0.1.3.

**Comment by chickenandpork** [comment]
Thanks!  :)   I'll permit the dependency update and ensure it resolves over here.
